spring.application.name=URLShortner
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache config
spring.cache.type=redis
spring.spring.cache.redis.time-to-live=3600000


# cache null values to avoid DB hammering on missing keys
spring.cache.redis.cache-null-values=false

# prefix all cache keys with app name to avoid conflicts
spring.cache.redis.key-prefix=urlshortener:

# show cache activity in logs during development
logging.level.org.springframework.cache=TRACE