spring.application.name=URLShortner
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379


# show cache activity in logs during development
logging.level.org.springframework.cache=TRACE

# Which endpoints to expose
management.endpoints.web.exposure.include=health,metrics,info
# Show full health details including DB and Redis status
management.endpoint.health.show-details=always
# Enable info endpoint
management.info.env.enabled=true

# These show up at /actuator/info
info.app.name=URL Shortener
info.app.description=URL shortener with Redis caching
info.app.version=1.0.0